- name: Installing dependencies
  apt: name={{item}} state=installed
  with_items:
    - s3cmd
    - git
    - libfreetype6-dev
    - pkg-config
    - libpng12-dev
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - libharfbuzz-dev
    - libfribidi-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk

- name: Fetch alpenglow repository
  git:
    repo: https://github.com/tpawlowski/alpenglow.git
    dest: /home/ubuntu/alpenglow
    version: master
  become: yes
  become_user: "{{ansible_user}}"

- name: Installing venv
  command: virtualenv /home/ubuntu/alpenglow/venv_heron creates="/home/ubuntu/alpenglow/venv_heron"
  become: yes
  become_user: "{{ansible_user}}"

- name: Install requirements
  pip:
    requirements=/home/ubuntu/alpenglow/requirements.txt
    virtualenv=/home/ubuntu/alpenglow/venv_heron
  become: yes
  become_user: "{{ansible_user}}"

- name: Copy aws credentials
  copy:
    dest: "/home/{{ansible_user}}/.s3cfg"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0600
    content: |
      [default]
      access_key = {{ AWSAccessKeyId }}
      secret_key = {{ AWSSecretKey }}