# Based on https://apache.github.io/incubator-heron/docs/operators/deployment/schedulers/standalone/
#
# run cluster with command:
#   heron-admin standalone cluster start
#

- name: Upload inventory
  template:
    src: inventory.yaml.j2
    dest: "/home/{{ ansible_user }}/.heron/conf/standalone/inventory.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755