- name: Download aurora deb
  get_url:
    url: https://apache.bintray.com/aurora/ubuntu-{{ ansible_distribution_release }}/aurora-tools_{{ aurora_version }}_amd64.deb
    dest: /tmp/aurora-tools_{{ aurora_version }}_amd64.deb

- name: Install aurora client
  apt:
    deb: /tmp/aurora-tools_{{ aurora_version }}_amd64.deb
