- hosts: all
  gather_facts: False
  name: Install dependencies for alpenglow no-framework benchmark
  become: yes
  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'download', tags: 'download'}
